apiVersion: apps/v1
kind: Deployment
metadata:
  name: uda-final
  labels:
    app: uda-final
spec:
  # progressDeadlineSeconds: 3600
  replicas: 3
  selector:
    matchLabels:
      app: uda-final
  # strategy:
  #   rollingUpdate:
  #     maxSurge: 25%
  #     maxUnavailable: 25%
  #   type: RollingUpdate
  template:
    metadata:
      labels:
        app: uda-final
    spec:
      containers:
        - image: dienpp/uda-final:latest
          imagePullPolicy: Always
          name: uda-final
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: uda-final
  labels:
    app: uda-final
spec:
  type: LoadBalancer
  selector:
    app: uda-final
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
